- name: Seup Hostname
  hostname:
    name: "{{ inventory_hostname }}"
- name: Setup modules on Debian hosts
  community.general.modprobe:
    name: "{{ item }}"
    state: present
  loop: "{{ g02_modulos }}"
- name: Setup sysctl setting {{ item }}
  ansible.posix.sysctl:
    name: "{{ item }}"
    value: 1
    state: present
  loop: "{{ g02_sysctl }}"
- name: Check if there is any swap partition enabled on host
  ansible.builtin.shell: "lsblk"
  register: lsblk_output
  ignore_errors: true
- name: Display swap information
  command: "swapon -s"
  register: swap_info

- name: Disable SWAP since kubernetes can't work with swap enabled (1/2)
  ansible.builtin.shell: |
    swapoff -a
  when: ("'[SWAP]' in lsblk_output.stdout_lines") or (swap_info.stdout_lines | length > 1)
- name: Disable SWAP in fstab since kubernetes can't work with swap enabled (2/2)
  ansible.builtin.replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    replace: '# \1'
- name: Install necessary packages
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - curl

# - name: Update Debian hosts
#   ansible.builtin.apt:
#     upgrade: dist
#     force_apt_get: true
# notify: Restart_hosts
- name: Add apt key
  ansible.builtin.apt_key:
    url: "{{ k8s_key }}"
    state: present
- name: Add repository
  ansible.builtin.apt_repository:
    repo: "{{ k8s_repo }}"
    state: present
