
- name: Install containerd
  ansible.builtin.apt:
    name: containerd
    state: present
- name: Add kubernet packages
  ansible.builtin.apt:
    name:
      - kubelet={{ k8s_version | default('1.27.0-00') }}
      - kubeadm={{ k8s_version | default('1.27.0-00') }}
      - kubectl={{ k8s_version | default('1.27.0-00') }}
- name: Set hold on packages
  ansible.builtin.dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop:
    - kubelet
    - kubeadm
    - kubectl
