---
- name: Setup host
  hosts: linux_server
  become: true

  tasks:
    - name: Create svc_ansible user
      ansible.builtin.user:
        name: svc_ansible
        state: present
    - name: Copy your id_rsa.pub
      ansible.posix.authorized_key:
        user: svc_ansible
        key: "{{lookup('file','/root/.ssh/id_rsa.pub')}}"
    - name: Configure sudo
      ansible.builtin.copy:
        content: "svc_ansible ALL=(ALL) NOPASSWD: ALL"
        dest: "/etc/sudoers.d/svc_ansible"
        validate: visudo -csf %s
        owner: root
        mode: o+r,g+r,o-rwx
