---
- name: Setup K8S Cluster
  hosts: k8s_cluster
  become: true
  vars:
    k8s_version: 1.29.0-00
    k8s_key: https://pkgs.k8s.io/core:/stable:/v1.29/deb/Release.key
    k8s_repo: "eb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.29/deb/ /"

  roles:
    - role: g02-k8s-cluster
